version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: bdmongo
    volumes:
      - ./data:/data/db
  api:
    build: api/.
    ports:
      - 8086:8086
    environment:
      - PORT=8086
    depends_on:
      - mongodb